repos:
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        name: detect-secrets (prevent committing secrets)
        args: ["--baseline", ".secrets.baseline"]
        exclude: "(package-lock.json|yarn.lock|pnpm-lock.yaml)"
  - repo: local
    hooks:
      - id: forbidden-pem
        name: Block committing *.pem / private keys
        entry: bash -c 'if grep -q "BEGIN PRIVATE KEY" "$@"; then echo "Private key material detected"; exit 1; fi'
        language: system
        files: ".*\.(pem|key|crt)$"
